version: '3.5'

services:
  db_labs:
    build: ./setup
    container_name: db_labs
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=docker_root
      - POSTGRES_USER=admin
    image: postgres:14.5-bullseye
